player.setav Acrobatics 1
player.setav Alchemy 1
player.setav Alteration 1
player.setav Armorer 1
player.setav Athletics 1
player.setav Blade 1
player.setav Block 1
player.setav Blunt 1
player.setav Conjuration 1
player.setav Destruction 1
player.setav HandToHand 1
player.setav HeavyArmor 1
player.setav Illusion 1
player.setav LightArmor 1
player.setav Marksman 1
player.setav Mercantile 1
player.setav Mysticism 1
player.setav Restoration 1
player.setav Security 1
player.setav Sneak 1
player.setav Speechcraft 1
